exclude: |
  ^data/(mini_tokens\.json|synth_labels\.json|synth_tokens\.json)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [json]
      - id: end-of-file-fixer
        exclude_types: [json]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-ast
      - id: check-case-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: forbid-bom
        name: Forbid UTF-8 BOM in text files
        entry: python scripts/check_no_bom.py
        language: system
        files: \.(md|ps1|py|txt|ya?ml)$
