name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            env/requirements.lock
            env/requirements.txt

      - name: Install dependencies (hashed)
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r env/requirements.txt

      - name: Run pre-commit
        run: |
          pre-commit --version
          pre-commit run -a

      - name: Type check (mypy)
        run: |
          pip install mypy
          mypy src

      - name: Run tests
        run: |
          pytest -q
