name: CI

on:
  push:
  pull_request:

permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            env/requirements.lock
            env/dev-requirements.lock

      - name: Install runtime deps (hash-locked)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --require-hashes -r env/requirements.lock

      - name: Install dev tools (hash-locked)
        run: |
          python -m pip install --require-hashes -r env/dev-requirements.lock

      - name: Pre-commit (lint/format/policy)
        run: python -m pre_commit run --all-files

      - name: Mypy (type checks)
        run: python -m mypy src

      - name: Validate summary/provenance
        run: python scripts/check_summary.py

      - name: Tests with coverage
        run: python -m pytest --cov=src --cov-report=term-missing --cov-fail-under=0 -q
