name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.os }} / py3.11)
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    concurrency:
      group: ci-${{ github.workflow }}-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.11'
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            env/requirements.lock
            env/dev-requirements.lock

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel

      - name: Install runtime dependencies
        run: pip install -r env/requirements.lock

      - name: Install dev dependencies
        run: pip install -r env/dev-requirements.lock

      - name: Pre-commit (lint & format)
        run: pre-commit run --all-files

      - name: Type check
        run: mypy src

      - name: Sanity check summary
        run: python scripts/check_summary.py

      - name: Run tests
        run: pytest -q