name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: env/requirements.lock

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r env/requirements.lock
          pip install pre-commit pytest

      - name: Pre-commit
        run: pre-commit run --all-files

      - name: Pytest
        run: pytest -q
